version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hellowikistack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1re48ohmsc2ep"
s3_prefix = "hellowikistack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
